name: GitHub Actions
run-name: ${{ github.actor }} is checking ${{ github.ref }} branch 🚀
#on: [push]
jobs:
  baseapp-core-workflow:
    uses: ./.github/workflows/project-workflow.yml
    with:
      project: baseapp-core
  baseapp-reactions-workflow:
    uses: ./.github/workflows/project-workflow.yml
    with:
      project: baseapp-reactions
